
version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  json:
    format: "%(asctime)s"
    class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: /var/log/vmware-mcp-server.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

  audit:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: /var/log/vmware-mcp-audit.log
    maxBytes: 10485760  # 10MB
    backupCount: 10

loggers:
  vmware_mcp:
    level: INFO
    handlers: [console, file]
    propagate: false

  vmware_mcp.audit:
    level: INFO
    handlers: [audit]
    propagate: false

  pyvmomi:
    level: WARNING
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console]
